
CREATE PROCEDURE SP_GET_CODIGO
AS
BEGIN
SELECT * FROM [CODIGOCLIENTE].[dbo].CODIGO

END
GO

CREATE PROCEDURE SP_GET_CODIGOU
	@PI_ID_CODIGO INT
AS
BEGIN
SELECT * FROM [CODIGOCLIENTE].[dbo].CODIGO
WHERE ID_CODIGO = @PI_ID_CODIGO
END
GO

CREATE PROCEDURE SP_INT_CODIGO
	@PV_DESCRIPCION VARCHAR(300),
	@PI_USUARIO_CREACION INT
AS
BEGIN
INSERT INTO [CODIGOCLIENTE].[dbo].CODIGO (DESCRIPCION, ESTADO, USUARIO_CREACION, FECHA_CREACION)
VALUES (@PV_DESCRIPCION, 'A', @PI_USUARIO_CREACION, GETDATE())
END
GO


CREATE PROCEDURE SP_DEL_CODIGO
	@PI_ID_CODIGO INT
AS
BEGIN
UPDATE  [CODIGOCLIENTE].[dbo].CODIGO 
SET ESTADO = 'I'
WHERE ID_CODIGO = @PI_ID_CODIGO
END
GO


CREATE PROCEDURE SP_UPD_CODIGO
	@PI_ID_CODIGO INT,
	@PV_DESCRIPCION VARCHAR(300)
AS
BEGIN
UPDATE  [CODIGOCLIENTE].[dbo].CODIGO 
SET DESCRIPCION = @PV_DESCRIPCION
WHERE ID_CODIGO = @PI_ID_CODIGO
END
GO