
CREATE PROCEDURE SP_GET_USUARIOXCODIGO
AS
BEGIN
SELECT * FROM [CODIGOCLIENTE].[dbo].USUARIOXCODIGO 
END
GO



CREATE PROCEDURE SP_GET_USUARIOXCODIGOU
	@PI_ID_USUXCOD INT
AS
BEGIN
SELECT * FROM [CODIGOCLIENTE].[dbo].USUARIOXCODIGO 
WHERE ID_USUXCOD = @PI_ID_USUXCOD
END
GO



CREATE PROCEDURE SP_INT_USUARIOXCODIGO
	@PI_ID_CODIGO INT,
	@PI_ID_USUARIO INT
AS
BEGIN
INSERT INTO [CODIGOCLIENTE].[dbo].USUARIOXCODIGO (ESTADO, ID_CODIGO, ID_USUARIO)
VALUES ('A', @PI_ID_CODIGO, @PI_ID_USUARIO)
END
GO

CREATE PROCEDURE SP_DEL_USUARIOXCODIGO
	@PI_ID_USUXCOD INT
AS
BEGIN
UPDATE [CODIGOCLIENTE].[dbo].USUARIOXCODIGO 
SET ESTADO = 'I'
WHERE ID_USUXCOD = @PI_ID_USUXCOD
END
GO

CREATE PROCEDURE SP_UPD_USUARIOXCODIGO
	@PI_ID_USUXCOD INT,
	@PI_ID_CODIGO INT,
	@PI_ID_USUARIO INT
AS
BEGIN
UPDATE [CODIGOCLIENTE].[dbo].USUARIOXCODIGO 
SET 
	ID_CODIGO= @PI_ID_CODIGO,
	ID_USUARIO = @PI_ID_USUARIO
WHERE ID_USUXCOD = @PI_ID_USUXCOD
END
GO