
CREATE TABLE USUARIOS   (
	[ID_USUARIO] [int] NOT NULL PRIMARY KEY IDENTITY(1,1),
	[NOMBRES] [varchar](100) NULL,
	[APELLIDOS] [varchar](100) NULL,
	[MAIL] [varchar](100) NULL,
	[FECHA_NACIMIENTO] [datetime] NULL,
	[CONTRASENA] [varchar](100) NULL,
	[ESTADO] [varchar](1) NULL ,
	[FECHA_ULTIMA_CONEXION] [datetime] NULL,
	[USUARIO_CREACION] [int] NULL,
	[FECHA_CREACION] [datetime] NULL,
	[USUARIO_MODIFICACION] [int] NULL,
	[FECHA_MODIFICACION] [datetime] NULL,

)


CREATE TABLE CODIGO   (
	ID_CODIGO [int] NOT NULL PRIMARY KEY IDENTITY(1,1),
	DESCRIPCION [varchar](300) NULL,
	[ESTADO] [varchar](1) NULL ,
	[USUARIO_CREACION] [int] NULL,
	[FECHA_CREACION] [datetime] NULL

)

GO

CREATE TABLE USUARIOXCODIGO   (
	ID_USUXCOD [int] NOT NULL PRIMARY KEY IDENTITY(1,1),
	ESTADO [varchar](1) NULL, 
	ID_CODIGO [int] NOT NULL,
	[ID_USUARIO] int NOT NULL,
	FOREIGN KEY (ID_CODIGO) REFERENCES CODIGO(ID_CODIGO),
	FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO)

)